[package]
name = "parcel_sourcemap_wasm"
version = "2.0.0-rc.2"
authors = ["Jasper De Moor <jasperdemoor@gmail.com>"]
edition = "2018"

[dependencies]
parcel_sourcemap = { path = "../parcel_sourcemap" }
