[package]
name = "parcel_sourcemap_wasm"
version = "2.0.1-rc.6"
authors = ["Jasper De Moor <jasperdemoor@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
opt-level = 's' # optimize for size
codegen-units = 1

[dependencies]
parcel_sourcemap = { path = "../parcel_sourcemap" }
