parameters:
  - name: 'name'
    type: string

jobs:
  - job: ${{ parameters.name }}
    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
          publish_artifacts: false
        node_14_x:
          node_version: 14.x
          publish_artifacts: true
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js'
      - script: yarn install --build-from-source
        displayName: Install dependencies
      - script: yarn run transpile
        displayName: Transpile and Generate Typings
      - script: yarn build:node-release
        displayName: Build production binaries
      - script: yarn run test:node
        displayName: Run tests (node)
