parameters:
  - name: 'name'
    type: string
  - name: 'vmImage'
    type: string
  - name: 'container'
    type: string
    default: ''
  - name: 'arch'
    type: string
    default: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    ${{ if ne(parameters.container, '') }}:
      container: ${{ parameters.container }}
    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
          publish_artifacts: false
        node_14_x:
          node_version: 14.x
          publish_artifacts: true
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
          force32bit: eq('${{ parameters.arch }}', 'ia32')
        displayName: 'Install Node.js'
      - script: npm install -g yarn
        displayName: 'Install yarn'
        condition: eq('${{ parameters.name }}', 'CentOS7')
      - script: yarn install --build-from-source
        displayName: Install dependencies
      - script: yarn run transpile
        displayName: Transpile and Generate Typings
      - script: yarn build:node-release
        displayName: Build production binaries

      - script: yarn run test:node
        displayName: Run tests (node)
      - script: ls -l */target/*
        displayName: List binaries
        
      - task: PublishBuildArtifacts@1
        displayName: Save binaries
        condition: and(succeeded(), eq(variables['publish_artifacts'], 'true'))
        inputs:
          artifactName: binaries
          pathtoPublish: '$(System.DefaultWorkingDirectory)/*/target/*'
