trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

jobs:
  - template: azure-pipelines-template.yml
    parameters:
      name: macOS
      vmImage: macOS-latest

  - template: azure-pipelines-template.yml
    parameters:
      name: Windows
      vmImage: windows-latest

  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      - job: Publish
        condition: succeeded()
        dependsOn:
          - macOS
          - Alpine
          - CentOS7
          - Windows
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: Download Native Artifacts
            inputs:
              artifactName: node-artifacts
              downloadPath: '$(System.DefaultWorkingDirectory)/parcel_sourcemap_node/artifacts'
          - script: npm install --build-from-source
            displayName: Install Node Modules
          - task: Npm@1
            displayName: NPM Release
            inputs:
              command: 'publish'
              publishEndpoint: npm
