trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

jobs:
  - template: azure-pipelines-template.yml
    parameters:
      name: macos-x64
      vmImage: macOS-latest

  - template: azure-pipelines-template.yml
    parameters:
      name: windows-x64
      vmImage: windows-latest

  - template: azure-pipelines-template.yml
    parameters:
      name: linux-gnu-x64
      vmImage: ubuntu-latest
