[package]
name = "parcel_sourcemap"
version = "0.1.0"
authors = ["Jasper De Moor <jasperdemoor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
