[package]
name = "parcel_sourcemap"
version = "2.0.0-rc.2"
authors = [ "Jasper De Moor <jasperdemoor@gmail.com>" ]
edition = "2018"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
"vlq" = "0.5.1"
"napi" = "1.6.1"
"serde" = { version = "1.0.126", features = ["derive"] }
"bincode" = "1.3.3"
