name: Benchmark
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: yarn build:node-release

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: bench-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: bench-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: bench-${{ hashFiles('yarn.lock') }}

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000
      - name: 'Run benchmark'
        run: yarn benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        if: github.ref != 'refs/heads/main'
        with:
          tool: 'benchmarkjs'
          output-file-path: bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
