name: Benchmark
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: 'Install dependencies'
        run: yarn install
      - name: Build code
        run: yarn transpile && yarn build:node-release
      - name: 'Run benchmark'
        run: yarn benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        if: github.ref != 'refs/heads/main'
        with:
          tool: 'benchmarkjs'
          output-file-path: bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
