name: Benchmark
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: bench-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: bench-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: bench-node-modules-${{ hashFiles('yarn.lock') }}

      - name: 'Install dependencies'
        run: yarn install
      - name: Build code
        run: yarn transpile && yarn build:node-release
      - name: 'Run benchmark'
        run: yarn benchmark

      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./benchmark-results
          key: benchmark-results-cache

      - name: Compare benchmark results
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'benchmarkjs'
          output-file-path: bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          external-data-json-path: ./benchmark-results/benchmark-data.json
          comment-always: true
          auto-push: false
          save-data-file: ${{ github.ref == 'refs/heads/master' }}

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
