name: Benchmark
on:
  push:
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: 'Install dependencies'
        run: yarn install
      - name: Build code
        run: yarn transpile && yarn build:node-release
      - name: 'Run benchmark'
        run: yarn benchmark

      # Run benchmark action
      - name: Compare benchmark results
        uses: rhysd/github-action-benchmark@v1.8.1
        with:
          name: Parcel Source Map library Benchmark
          tool: 'benchmarkjs'
          output-file-path: bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: public/bench
          auto-push: true # ${{ github.ref == 'refs/heads/master' }}
          comment-always: true

      # Deploy gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
